name = "sohoj-somadhan"
main = "src/worker.js" # এখানে আপনার মূল জাভাস্ক্রিপ্ট ফাইলের পাথ দিন (যেমন: src/worker.js বা index.js)
compatibility_date = "2026-09-03"

[[d1_databases]]
binding = "DB"
database_name = "sohoj-somadhan"
database_id = "4baf1936-cd75-4afe-baea-a729e6f27d3e"
