name = "sohoj-somadhan"
main = "src/worker.js"
compatibility_date = "2024-09-03"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "sohoj-somadhan"
database_id = "4baf1936-cd75-4afe-baea-a729e6f27d3e"